project:
  type: website
  output-dir: docs
  

website:
  title: "Blogs"
  navbar:
    right:
      - about.qmd
      - icon: github

      - icon: twitter
format:
  html:
    theme: morph
    css: styles.css

editor: visual

